services:
  texlive:
    image: paperist/texlive-ja:latest
    container_name: latex-env
    volumes:
      - .:/workdir
    working_dir: /workdir
    # LinuxやMacをお使いの場合、ファイルの所有権問題を避けるために以下を有効にしてください
    # user: "${UID}:${GID}"
    tty: true
    stdin_open: true